name: "Sigma Rule Deployer"
description: "Deploy alerts based on Sigma rules in Grafana"

inputs:
  config_path:
    description: "Path to the configuration file for the Sigma Rule Deployer"
    required: true
    default: ""
  grafana_sa_token:
    description: "Service account token for Grafana"
    required: true
    default: ""
  fresh_deploy:
    description: "If true, ALL the alert rules in the Grafana Alert folder specified in the config will be deleted, and the alerts in the deployment folder will be created from scratch. ⚠️ Warning: destructive action"
    required: false
    default: "false"

outputs:
  alerts_created:
    description: "List of alerts UIDs created in Grafana"
  alerts_updated:
    description: "List of alerts UIDs updated in Grafana"
  alerts_deleted:
    description: "List of alerts UIDs deleted in Grafana"

runs:
  using: "docker"
  image: "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:GITHUB_ACTION_SHA"
  args:
    - deploy
  env:
    CONFIG_PATH: ${{ inputs.config_path }}
    DEPLOYER_GRAFANA_SA_TOKEN: ${{ inputs.grafana_sa_token }}
    DEPLOYER_FRESH_DEPLOY: ${{ inputs.fresh_deploy }}
    ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
    MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
    DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
    COPIED_FILES: ${{ steps.changed-files.outputs.copied_files }} 