name: "Sigma Rule Converter"
description: "Convert Sigma rules to target query languages using sigma-cli."
author: "Mostafa Moradian"

inputs:
  config_path:
    description: "Path to the Sigma conversion config file."
    required: true
    default: "./config.yaml"
  plugin_packages:
    description: "Comma-separated list of Sigma CLI plugin packages to install."
    required: false
    default: ""
  render_traceback:
    description: "Whether to render the traceback in the output."
    required: false
    default: "false"

runs:
  using: "docker"
  image: "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-converter:GITHUB_ACTION_SHA"
  args:
    - convert
  env:
    CONFIG_PATH: ${{ inputs.config_path }}
    RENDER_TRACEBACK: ${{ inputs.render_traceback }}
    PLUGIN_PACKAGES: ${{ inputs.plugin_packages }}
