version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Custom linters
    - asciicheck
    - bodyclose
    - dogsled
    - gofmt
    - exhaustive
    - forcetypeassert
    - goconst
    - gocritic
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - reassign
    - revive
    - unconvert
    - whitespace
    - prealloc
