name: Comment Sigma Results
description: Posts a comment to a PR with Sigma rule conversion/integration results, displaying rule titles from YAML files

inputs:
  pull_request_number:
    description: 'The pull request number'
    required: true
  changed_files:
    description: 'Space-separated list of changed files'
    required: true
  deleted_files:
    description: 'Space-separated list of deleted files'
    required: true
  comment_title:
    description: 'Title for the comment section (e.g., "Sigma Rule Conversions" or "Sigma Rule Integrations")'
    required: true
  comment_identifier:
    description: 'String to identify old comments for cleanup (typically same as comment_title)'
    required: true
  additional_content:
    description: 'Optional additional markdown content to append to the comment (e.g., Test Results table)'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: composite
  steps:
    - name: Generate PR Comment
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull_request_number }}
        CHANGED_FILES: ${{ inputs.changed_files }}
        DELETED_FILES: ${{ inputs.deleted_files }}
        COMMENT_TITLE: ${{ inputs.comment_title }}
        COMMENT_IDENTIFIER: ${{ inputs.comment_identifier }}
        ADDITIONAL_CONTENT: ${{ inputs.additional_content }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');
          const path = require('path');
          
          const changedFiles = process.env.CHANGED_FILES.split(' ').filter(file => file.trim() !== '');
          const deletedFiles = process.env.DELETED_FILES.split(' ').filter(file => file.trim() !== '');
          const commentTitle = process.env.COMMENT_TITLE;
          const commentIdentifier = process.env.COMMENT_IDENTIFIER;
          const additionalContent = process.env.ADDITIONAL_CONTENT;

          // Function to extract title from YAML file
          function extractTitle(filePath) {
            try {
              const content = fs.readFileSync(filePath, 'utf8');
              const titleMatch = content.match(/^title:\s*(.+)$/m);
              if (titleMatch && titleMatch[1]) {
                return titleMatch[1].trim();
              }
              // Fallback to filename if no title found
              return path.basename(filePath);
            } catch (error) {
              console.log(`Error reading file ${filePath}: ${error.message}`);
              // Fallback to filename if file can't be read
              return path.basename(filePath);
            }
          }

          const prData = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: process.env.PULL_REQUEST_NUMBER,
          });
          if (!prData.data) {
            console.log(`No pull request found for ${context.repo.owner}/${context.repo.repo}#${process.env.PULL_REQUEST_NUMBER}`);
            return '';
          }

          const nodeId = prData.data.node_id;

          // Build file list with titles
          const changedFilesList = changedFiles.map(file => {
            const title = extractTitle(file);
            return `- [${title}](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/${prData.data.head.ref}/${file})`;
          }).join("\n");

          const comment = `
          ### ${commentTitle}

          | Changed | Deleted |
          | --- | --- |
          | ${changedFiles.length} | ${deletedFiles.length} |

          ### Changed Files

          ${changedFiles.length ? changedFilesList : "No files changed"}

          ### Deleted Files

          ${deletedFiles.length ? deletedFiles.map(file => `- ${file}`).join("\n") : "No files deleted"}

          ${additionalContent ? '\n' + additionalContent : ''}
          `;

          const oldCommentQuery = `query GetPRComments($owner: String!, $name: String!, $number: Int!) {
              repository(owner: $owner, name: $name) {
                id
                pullRequest(number: $number) {
                  title
                  comments(last: 100) {
                    nodes {
                      id
                      bodyText
                      isMinimized
                      author {
                        login
                      }
                    }
                  }
                }
              }
          }`;

          const minimizeCommentMutation = `mutation MinimizeComment($subjectId: ID!) {
            minimizeComment(input: {
              subjectId: $subjectId,
              classifier: OUTDATED
            }) {
              clientMutationId
            }
          }`;

          const query = `mutation AddComment($body: String!, $subjectId: ID!) {
            addComment(input: {
              body: $body,
              subjectId: $subjectId,
            }) {
              subject {
                id
                ... on PullRequest {
                  number
                }
              }
            }
          }`

          const comments = await github.graphql(oldCommentQuery, {
            owner: context.repo.owner,
            name: context.repo.repo,
            number: parseInt(process.env.PULL_REQUEST_NUMBER, 10)
          });

          for (const comment of comments?.repository?.pullRequest?.comments?.nodes ?? []) {
            if (!comment.isMinimized && comment.bodyText.startsWith(commentIdentifier)) {
              await github.graphql(minimizeCommentMutation, {
                subjectId: comment.id
              });
            }
          }

          const variables = {
            body: comment,
            subjectId: nodeId
          };

          await github.graphql(query, variables);

          return '';

