name: "Grafana Query Integration"
description: "Take converted rules and convert them into deployable outputs (alert rules, dashboards, etc.) and test them."
author: "security-operations"

inputs:
  config_path:
    description: "Path to the configuration file for the Sigma Rule Deployer"
    required: true
    default: ""
  grafana_sa_token:
    description: "Service account token for Grafana for query testing"
    required: false
    default: ""
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}
  pretty_print:
    description: "Pretty print the JSON output"
    required: false
    default: "false"
  output_log_lines:
    description: "Output log lines to the outputs of the test_query_results"
    required: false
    default: "false"
  all_rules:
    description: "Whether to integrate all rules"
    required: false
    default: "false"
  conversion_path:
    description: "The path to the conversion folder"
    required: false
    default: "./conversions"

outputs:
  rules_integrated:
    description: "The repository file names changed (added/updated or removed) by this Action"
    value: ${{ steps.set-output.outputs.rules_integrated }}
  test_query_results:
    description: "The results of testing the queries against the datasource for the past hour"
    value: ${{ steps.set-output.outputs.test_query_results }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Get Last Commit or base_ref
      if: ${{ github.event_name == 'pull_request' && inputs.changed_files_from_base == 'false' }}
      id: last-commit
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      env:
        ACTIONS_USERNAME: ${{ inputs.actions_username }}
      with:
        script: |
          const iterator = github.paginate(github.rest.pulls.listCommits, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            per_page: 1
          });
          let commit = "";
          for await (const { data } of iterator) {
            if (commit === "") {
              commit = data[0].sha;
            }
            for (const { commit } of data) {
              if (commit.committer.name === process.env.ACTIONS_USERNAME) {
                commit = commit.sha;
              }
            }
          }
          return commit;
        result-encoding: string
    - name: Calculate Change Files
      id: changed-files
      shell: bash
      env:
        CONVERSION_PATH: ${{ inputs.conversion_path }}
        BASE_REF: ${{ steps.last-commit.outputs.result || github.base_ref || github.event.pull_request.base.ref || 'origin/HEAD' }}
      run: |
        git fetch
        CHANGED_FILES=$(git diff --name-only $BASE_REF --diff-filter=ACMR -- $CONVERSION_PATH)
        DELETED_FILES=$(git diff --name-only $BASE_REF --diff-filter=D -- $CONVERSION_PATH)
        echo all_changed_files=${CHANGED_FILES//\\n/} >> "$GITHUB_OUTPUT"
        echo deleted_files=${DELETED_FILES//\\n/} >> "$GITHUB_OUTPUT"

    - name: Run Sigma Rule Integrator
      id: integrate
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_path }}
        GRAFANA_SA_TOKEN: ${{ inputs.grafana_sa_token }}
        PRETTY_PRINT: ${{ inputs.pretty_print }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        ALL_RULES: ${{ inputs.all_rules }}
        ACTION_REF: ${{ github.action_ref }}
      run: |
        docker run --rm \
            -v "$(pwd):/sigma-rules" \
            -w /sigma-rules \
            -e GITHUB_OUTPUT=/sigma-rules/github-output \
            -e INTEGRATOR_CONFIG_PATH="$CONFIG_PATH" \
            -e INTEGRATOR_GRAFANA_SA_TOKEN="$GRAFANA_SA_TOKEN" \
            -e PRETTY_PRINT="$PRETTY_PRINT" \
            -e CHANGED_FILES="$CHANGED_FILES" \
            -e DELETED_FILES="$DELETED_FILES" \
            -e ALL_RULES="$ALL_RULES" \
            "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-$ACTION_REF" \
            integrate
    - name: Set output
      id: set-output
      shell: bash
      run: |
        mv github-output $GITHUB_OUTPUT
