name: "Grafana Query Integration"
description: "Take converted rules and convert them into deployable outputs (alert rules, dashboards, etc.) and test them."
author: "security-operations"

inputs:
  config_path:
    description: "Path to the configuration file for the Sigma Rule Deployer"
    required: true
    default: ""
  grafana_sa_token:
    description: "Service account token for Grafana for query testing"
    required: false
    default: ""
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}

outputs:
  rules_integrated:
    description: "The repository file names changed (added/updated or removed) by this Action"
    value: ${{ steps.integrate.outputs.rules_integrated }}

runs:
  using: "composite"
  steps:
    - name: "Checkout repository (fetch-depth: 0)"
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important to ensure we'll have all the commits when a merge includes multiple

    - name: "Setup Actions"
      uses: actions/checkout@v4
      env:
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _sigma-rule-deployment
        persist-credentials: false
        token: ${{ inputs.github_token }}
    - name: "Detect changed files"
      id: changed-files
      uses: grafana/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
      with:
        output_renamed_files_as_deleted_and_added: "true"

    - name: "Substitute action version"
      shell: bash
      id: substitute-action-version
      env:
        action_ref: ${{ github.action_ref }}
      run: |
        sed -i "s/GITHUB_ACTION_SHA/${{ env.action_ref }}/g" ./_sigma-rule-deployment/actions/integrate-docker/action.yml
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Run Sigma Rule Converter
      id: convert
      shell: bash
      env:
        action_ref: ${{ github.action_ref }}
      run: |
        docker pull "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-converter:${{ env.action_ref }}"
        docker run --rm -v "$(pwd):/sigma-rules" -w /sigma-rules -e INTEGRATOR_CONFIG_PATH="${{ inputs.config_path }}" -e INTEGRATOR_GRAFANA_SA_TOKEN="${{ inputs.grafana_sa_token }}" -e ADDED_FILES="${{ steps.changed-files.outputs.added_files }}" -e MODIFIED_FILES="${{ steps.changed-files.outputs.modified_files }}" -e DELETED_FILES="${{ steps.changed-files.outputs.deleted_files }}" -e COPIED_FILES="${{ steps.changed-files.outputs.copied_files }}" "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-converter:${{ env.action_ref }}" integrate
    - name: Commit integrated queries
      uses: stefanzweifel/git-auto-commit-action@v4