name: "Grafana Query Integration"
description: "Take converted rules and convert them into deployable outputs (alert rules, dashboards, etc.) and test them."
author: "security-operations"

inputs:
  config_path:
    description: "Path to the configuration file for the Sigma Rule Deployer"
    required: true
    default: ""
  grafana_sa_token:
    description: "Service account token for Grafana for query testing"
    required: false
    default: ""
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}
  pretty_print:
    description: "Pretty print the JSON output"
    required: false
    default: "false"
  output_log_lines:
    description: "Output log lines to the outputs of the test_query_results"
    required: false
    default: "false"
  all_rules:
    description: "Whether to integrate all rules"
    required: false
    default: "false"
  changed_files:
    description: "The changed files to integrate"
    required: false
    default: ""
  deleted_files:
    description: "The deleted files to integrate"
    required: false
    default: ""

outputs:
  rules_integrated:
    description: "The repository file names changed (added/updated or removed) by this Action"
    value: ${{ steps.set-output.outputs.rules_integrated }}
  test_query_results:
    description: "The results of testing the queries against the datasource for the past hour"
    value: ${{ steps.set-output.outputs.test_query_results }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Run Sigma Rule Integrator
      id: integrate
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_path }}
        GRAFANA_SA_TOKEN: ${{ inputs.grafana_sa_token }}
        PRETTY_PRINT: ${{ inputs.pretty_print }}
        CHANGED_FILES: ${{ inputs.changed_files }}
        DELETED_FILES: ${{ inputs.deleted_files }}
        ALL_RULES: ${{ inputs.all_rules }}
        ACTION_REF: ${{ github.action_ref }}
      run: |
        docker run --rm \
            -v "$(pwd):/sigma-rules" \
            -w /sigma-rules \
            -e GITHUB_OUTPUT=/sigma-rules/github-output \
            -e INTEGRATOR_CONFIG_PATH="$CONFIG_PATH" \
            -e INTEGRATOR_GRAFANA_SA_TOKEN="$GRAFANA_SA_TOKEN" \
            -e PRETTY_PRINT="$PRETTY_PRINT" \
            -e CHANGED_FILES="$CHANGED_FILES" \
            -e DELETED_FILES="$DELETED_FILES" \
            -e ALL_RULES="$ALL_RULES" \
            "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-$ACTION_REF" \
            integrate
    - name: Set output
      id: set-output
      shell: bash
      run: |
        mv github-output $GITHUB_OUTPUT
