name: "Grafana Query Integration"
description: "Take converted rules and convert them into deployable outputs (alert rules, dashboards, etc.) and test them."
author: "security-operations"

inputs:
  config_path:
    description: "Path to the configuration file for the Sigma Rule Deployer"
    required: true
    default: ""
  grafana_sa_token:
    description: "Service account token for Grafana for query testing"
    required: false
    default: ""
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}

outputs:
  rules_integrated:
    description: "The repository file names changed (added/updated or removed) by this Action"
    value: ${{ steps.integrate.outputs.rules_integrated }}

runs:
  using: "composite"
  steps:
    - name: "Checkout repository (fetch-depth: 0)"
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important to ensure we'll have all the commits when a merge includes multiple

    - name: "Setup Actions"
      uses: actions/checkout@v4
      env:
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _sigma-rule-deployment
        persist-credentials: false
        token: ${{ inputs.github_token }}
    - name: "Detect changed files"
      id: changed-files
      uses: grafana/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
      with:
        output_renamed_files_as_deleted_and_added: "true"

    - name: "Substitute action version"
      shell: bash
      id: substitute-action-version
      env:
        action_ref: ${{ github.action_ref }}
      run: |
        sed -i "s/GITHUB_ACTION_SHA/${{ env.action_ref }}/g" ./_sigma-rule-deployment/actions/integrate-docker/action.yml
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - name: "Run Sigma Rule Integrator"
      id: integrate
      uses: ./_sigma-rule-deployment/actions/integrate-docker
      with:
        config_path: ${{ inputs.config_path }}
        grafana_sa_token: ${{ inputs.grafana_sa_token }}
        added_files: ${{ steps.changed-files.outputs.added_files }}
        modified_files: ${{ steps.changed-files.outputs.modified_files }}
        deleted_files: ${{ steps.changed-files.outputs.deleted_files }}
        copied_files: ${{ steps.changed-files.outputs.copied_files }}

    - name: Commit integrated queries
      uses: stefanzweifel/git-auto-commit-action@v4