name: "Sigma Rule Converter"
description: "Convert Sigma rules to target query languages using sigma-cli."
author: "Mostafa Moradian"

inputs:
  config_path:
    description: "Path to the Sigma conversion config file."
    required: true
    default: "./config.yaml"
  plugin_packages:
    description: "Comma-separated list of Sigma CLI plugin packages to install."
    required: false
    default: ""
  render_traceback:
    description: "Whether to render the traceback in the output."
    required: false
    default: "false"
  pretty_print:
    description: "Pretty print the JSON output"
    required: false
    default: "false"
  all_rules:
    description: "Convert all rules specified in the config file."
    required: false
    default: "false"
  actions_username:
    description: "Username of the automation that commits conversions"
    required: false
    default: "github-actions[bot]"
  changed_files_from_base:
    description: "Whether to use the changed files from the base branch"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Retrieve conversion and deployment paths from config
      id: config-paths
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_path }}
      run: |
        CONVERSION_PATH=$(yq -r '.folders.conversion_path' "${CONFIG_PATH}")
        echo "conversion_path=${CONVERSION_PATH}" >> $GITHUB_OUTPUT
    - name: Login to GitHub Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Identify relevant commits
      if: ${{ inputs.changed_files_from_base == 'false' }}
      id: commits
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        ACTIONS_USERNAME: ${{ inputs.actions_username }}
      with:
        script: |
          const iterator = await github.paginate(github.rest.pulls.listCommits.endpoint.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            per_page: 1
          }));
          let previous_commit = "";
          let first_commit = "";
          let last_commit = "";
          let base_commit = "";
          for (const remote_commit of iterator) {
            if (previous_commit === "" && remote_commit.parents.length > 0) {
              previous_commit = remote_commit.parents[0].sha;
              base_commit = remote_commit.parents[0].sha;
              first_commit = remote_commit.sha;
            }
            if (remote_commit.commit.author.name === process.env.ACTIONS_USERNAME) {
              previous_commit = remote_commit.sha;
              last_commit = remote_commit.sha;
            }
          }
          console.log(`Base commit or base ref: ${base_commit}`);
          console.log(`Last commit or base ref: ${previous_commit}`);
          console.log(`PR First Commit: ${first_commit}`);
          console.log(`PR Last Commit by automation: ${last_commit}`);
          console.log(`PR Previous Ref: ${last_commit || previous_commit}`);

          core.setOutput('base-commit', base_commit);
          core.setOutput('previous-commit', previous_commit);
          core.setOutput('first-commit', first_commit);
          core.setOutput('last-commit', last_commit);
          core.setOutput('previous-ref', last_commit || previous_commit);

          return {};

    - name: Get Changed Files
      id: changed-files
      shell: bash
      env:
        PREVIOUS_REF: ${{ steps.commits.outputs.previous-ref }}
        CONVERSION_PATH: ${{ steps.config-paths.outputs.conversion_path }}
        CONFIG_PATH: ${{ inputs.config_path }}
      run: |
        # Diff Commands are constructed in conversion to discover the change for the **inputs** into the conversion process. This means that changes to the configuration or rules will
        # be registered as changed files, **but** changes to the output file will not register a change and will cause the conversion to pass but not run.

        ACMR_DIFF_COMMAND="git diff ${PREVIOUS_REF} --name-only --diff-filter=ACMR -- '${CONFIG_PATH}' $(yq -r "[.conversions.[].input] | flatten | unique | [\"':(glob)\" + .[] + \"'\"] | join(\" \")" ${CONFIG_PATH}) $(yq -r "[.conversions.[].pipelines] | flatten | unique | [\"':(glob)\" + .[] + \"'\"] | join(\" \")" ${CONFIG_PATH})"
        D_DIFF_COMMAND="git diff ${PREVIOUS_REF} --name-only --diff-filter=D -- '${CONFIG_PATH}' $(yq -r "[.conversions.[].input] | flatten | unique | [\"':(glob)\" + .[] + \"'\"] | join(\" \")" ${CONFIG_PATH}) $(yq -r "[.conversions.[].pipelines] | flatten | unique | [\"':(glob)\" + .[] + \"'\"] | join(\" \")" ${CONFIG_PATH})"

        # We want to only include the input files in the lists of changed and deleted files
        CHANGED_FILES=$(eval $ACMR_DIFF_COMMAND)
        DELETED_FILES=$(eval $D_DIFF_COMMAND)

        echo all_changed_files=${CHANGED_FILES//\\n/} >> "$GITHUB_OUTPUT"
        echo deleted_files=${DELETED_FILES//\\n/} >> "$GITHUB_OUTPUT"

    - name: Determine Image Reference
      id: image-ref
      shell: bash
      env:
        ACTION_REF: ${{ github.action_ref }}
      run: |
        # Check if the ACTION_REF is a tag (starts with v followed by numbers/dots)
        if [[ "$ACTION_REF" =~ ^v[0-9]+(\.[0-9]+)*(\.[0-9]+)?$ ]]; then
          echo "image_ref=$ACTION_REF" >> $GITHUB_OUTPUT
          echo "Using tag: $ACTION_REF"
        elif [[ "$ACTION_REF" == "latest" ]]; then
          echo "image_ref=main" >> $GITHUB_OUTPUT
          echo "Using main tag"
        else
          echo "image_ref=sha-$ACTION_REF" >> $GITHUB_OUTPUT
          echo "Using SHA: sha-$ACTION_REF"
        fi

    - name: Run Sigma Rule Converter
      id: convert
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_path }}
        PLUGIN_PACKAGES: ${{ inputs.plugin_packages }}
        RENDER_TRACEBACK: ${{ inputs.render_traceback }}
        PRETTY_PRINT: ${{ inputs.pretty_print }}
        ALL_RULES: ${{ inputs.all_rules }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        IMAGE_REF: ${{ steps.image-ref.outputs.image_ref }}
      run: |
        docker run --rm \
            -v "$(pwd):/sigma-rules" \
            -w /sigma-rules \
            -e GITHUB_WORKSPACE=/sigma-rules \
            -e CONFIG_PATH="$CONFIG_PATH" \
            -e PLUGIN_PACKAGES="$PLUGIN_PACKAGES" \
            -e RENDER_TRACEBACK="$RENDER_TRACEBACK" \
            -e PRETTY_PRINT="$PRETTY_PRINT" \
            -e ALL_RULES="$ALL_RULES" \
            -e CHANGED_FILES="$CHANGED_FILES" \
            -e DELETED_FILES="$DELETED_FILES" \
            "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:$IMAGE_REF" \
            convert

    - name: Generate Comment Data
      id: generate-comment-data
      shell: bash
      env:
        BASE_REF: ${{ steps.commits.outputs.base-commit }}
        CONVERSION_PATH: ${{ steps.config-paths.outputs.conversion_path }}
      run: |
        git add "$CONVERSION_PATH"
        CHANGED_FILES=$(git diff "$BASE_REF" --name-only --diff-filter=ACMR -- "$CONVERSION_PATH")
        DELETED_FILES=$(git diff "$BASE_REF" --name-only --diff-filter=D -- "$CONVERSION_PATH")
        echo changed_files=${CHANGED_FILES//\\n/} >> $GITHUB_OUTPUT
        echo deleted_files=${DELETED_FILES//\\n/} >> $GITHUB_OUTPUT

    - name: Comment Conversions
      id: comment-conversions
      uses: ./actions/comment-sigma-results@147dbafe8d4be1a24b8cca3e4801fc363fa4dbe1
      with:
        pull_request_number: ${{ github.event.number || github.event.issue.number }}
        changed_files: ${{ steps.generate-comment-data.outputs.changed_files }}
        deleted_files: ${{ steps.generate-comment-data.outputs.deleted_files }}
        comment_title: 'Sigma Rule Conversions'
        comment_identifier: 'Sigma Rule Conversions'
        github_token: ${{ github.token }}
