name: "Sigma CLI Conversion"
description: "Convert Sigma rules to target query languages using sigma-cli."
author: "Your Name"

inputs:
  rule_file:
    description: "Path to the Sigma rule file inside the repository"
    required: true
  target:
    description: "Target query language (e.g., loki, splunk, etc.)"
    required: true

outputs:
  result:
    description: "The converted query result"

runs:
  using: "composite"
  steps:
    - name: "Run Sigma CLI Conversion"
      run: |
        chmod +x action.sh
        ./action.sh convert -t ${{ inputs.target }} ${{ inputs.rule_file }} > result.txt

    - name: "Set result output"
      id: set_output
      run: echo "result=$(cat result.txt)" >> $GITHUB_ENV
