name: "Sigma Rule Converter"
description: "Convert Sigma rules to target query languages using sigma-cli."
author: "Mostafa Moradian"

inputs:
  config_path:
    description: "Path to the Sigma conversion config file."
    required: true
    default: "./config.yaml"
  plugin_packages:
    description: "Comma-separated list of Sigma CLI plugin packages to install."
    required: false
    default: ""
  render_traceback:
    description: "Whether to render the traceback in the output."
    required: false
    default: "false"
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}
  pretty_print:
    description: "Pretty print the JSON output"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Run Sigma Rule Converter
      id: convert
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_path }}
        PLUGIN_PACKAGES: ${{ inputs.plugin_packages }}
        RENDER_TRACEBACK: ${{ inputs.render_traceback }}
        PRETTY_PRINT: ${{ inputs.pretty_print }}
        action_ref: ${{ github.action_ref }}
      run: |
        docker pull ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${{ env.action_ref }}
        docker run --rm -v "$(pwd):/sigma-rules" -w /sigma-rules -e GITHUB_WORKSPACE=/sigma-rules -e CONFIG_PATH="${CONFIG_PATH}" -e PLUGIN_PACKAGES="${PLUGIN_PACKAGES}" -e RENDER_TRACEBACK="${RENDER_TRACEBACK}" -e PRETTY_PRINT="${PRETTY_PRINT}" ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${action_ref} convert
