name: "Sigma Rule Converter"
description: "Convert Sigma rules to target query languages using sigma-cli."
author: "Mostafa Moradian"

inputs:
  config_path:
    description: "Path to the Sigma conversion config file."
    required: true
    default: "./config.yaml"
  plugin_packages:
    description: "Comma-separated list of Sigma CLI plugin packages to install."
    required: false
    default: ""
  render_traceback:
    description: "Whether to render the traceback in the output."
    required: false
    default: "false"
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Run Sigma Rule Converter
      id: convert
      shell: bash
      env:
        action_ref: ${{ github.action_ref }}
      run: |
        docker pull ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${{ env.action_ref }}
        docker run --rm -v "$(pwd):/sigma-rules" -w /sigma-rules -e GITHUB_WORKSPACE=/sigma-rules -e CONFIG_PATH="${{ inputs.config_path }}" -e PLUGIN_PACKAGES="${{ inputs.plugin_packages }}" -e RENDER_TRACEBACK="${{ inputs.render_traceback }}" ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${{ env.action_ref }} convert
