name: "Sigma Rule Converter"
description: "Convert Sigma rules to target query languages using sigma-cli."
author: "Mostafa Moradian"

inputs:
  config_path:
    description: "Path to the Sigma conversion config file."
    required: true
    default: "./config.yaml"
  plugin_packages:
    description: "Comma-separated list of Sigma CLI plugin packages to install."
    required: false
    default: ""
  render_traceback:
    description: "Whether to render the traceback in the output."
    required: false
    default: "false"
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: "Checkout Actions"
      uses: actions/checkout@v4
      env:
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _sigma-rule-deployment
        persist-credentials: false
        token: ${{ inputs.github_token }}
    - name: "Substitute action version"
      shell: bash
      id: substitute-action-version
      env:
        action_ref: ${{ github.action_ref }}
      run: |
        sed -i "s/GITHUB_ACTION_SHA/${{ env.action_ref }}/g" ./_sigma-rule-deployment/actions/convert-docker/action.yml
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: "Run Sigma Rule Converter"
      uses: ./_sigma-rule-deployment/actions/convert-docker
      with:
        config_path: ${{ inputs.config_path }}
        plugin_packages: ${{ inputs.plugin_packages }}
        render_traceback: ${{ inputs.render_traceback }}
