name: "Sigma Rule Deployer"
description: "Deploy alerts based on Sigma rules in Grafana"

inputs:
  config_path:
    description: "Path to the configuration file for the Sigma Rule Deployer"
    required: true
    default: ""
  grafana_sa_token:
    description: "Service account token for Grafana"
    required: true
    default: ""
  fresh_deploy:
    description: "If true, ALL the alert rules in the Grafana Alert folder specified in the config will be deleted, and the alerts in the deployment folder will be created from scratch. ⚠️ Warning: destructive action"
    required: false
    default: "false"
  github_token:
    description: "GitHub token to use for the action."
    required: false
    default: ${{ github.token }}

outputs:
  alerts_created:
    description: "List of alerts UIDs created in Grafana"
    value: ${{ steps.deploy.outputs.alerts_created }}
  alerts_updated:
    description: "List of alerts UIDs updated in Grafana"
    value: ${{ steps.deploy.outputs.alerts_updated }}
  alerts_deleted:
    description: "List of alerts UIDs deleted in Grafana"
    value: ${{ steps.deploy.outputs.alerts_deleted }}

runs:
  using: "composite"
  steps:
    - name: "Checkout repository (fetch-depth: 0)"
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important to ensure we'll have all the commits when a merge includes multiple
    - name: "Detect changed files"
      id: changed-files
      uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
      with:
        output_renamed_files_as_deleted_and_added: "true"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Run Sigma Rule Deployer
      id: deploy
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config_path }}
        GRAFANA_SA_TOKEN: ${{ inputs.grafana_sa_token }}
        FRESH_DEPLOY: ${{ inputs.fresh_deploy }}
        ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
        DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        COPIED_FILES: ${{ steps.changed-files.outputs.copied_files }}
        action_ref: ${{ github.action_ref }}
      run: |
        docker pull ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${{ env.action_ref }}
        docker run --rm -v "$(pwd):/sigma-rules" -w /sigma-rules -e GITHUB_OUTPUT="${GITHUB_OUTPUT}" -e CONFIG_PATH="${CONFIG_PATH}" -e DEPLOYER_GRAFANA_SA_TOKEN="${GRAFANA_SA_TOKEN}" -e DEPLOYER_FRESH_DEPLOY="${FRESH_DEPLOY}" -e ADDED_FILES="${ADDED_FILES}" -e MODIFIED_FILES="${MODIFIED_FILES}" -e DELETED_FILES="${DELETED_FILES}" -e COPIED_FILES="${COPIED_FILES}" ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${action_ref} deploy
