name: Deploy Sigma rules

on:
  push:
    branches:
      - main
    paths:
      - "deployments/*.json"

jobs:
  deploy:
    permissions:
      contents: read # to read deployment files
      id-token: write # to get vault secrets
      packages: read # to pull the Action docker image
      pull-requests: write # to update the relevant pull request
    uses: grafana/sigma-rule-deployment/.github/workflows/deploy.yml@00595f30b410d688dd9dbd4b69b683da1a5f4800
    with:
      config_path: ./config.yml
    secrets:
      grafana_sa_token: ${{ secrets.GRAFANA_SA_TOKEN }}
