name: Deploy Sigma rules

on:
  push:
    branches:
      - main
    paths:
      - "deployments/**.json"
      - "config.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Sigma rules
        id: deploy
        uses: grafana/sigma-rule-deployment/actions/deploy@9951907447e9b3c5c36cb2cdf216480f474131f6
        with:
          config_path: "./config.yml"
          grafana_sa_token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
