name: Actionlint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

permissions: {}

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: raven-actions/actionlint@963d4779ef039e217e5d0e6fd73ce9ab7764e493 # v2.1.0
        with:
          files: ".github/workflows/*.yml,.github/workflows/*.yaml"
          fail-on-error: true
          cache: false
