name: "Build Consolidated Image"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4
            - name: "Login to GitHub Container Registry"
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: "Docker Metadata"
              id: docker-meta
              uses: docker/metadata-action@v5
              with:
                  images: "ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer"
                  tags: |
                      type=sha,format=short

            - name: "Build and Push"
              uses: docker/build-push-action@v4
              with:
                  context: ./actions
                  file: actions/Dockerfile
                  tags: ${{ steps.docker-meta.outputs.tags }}
                  labels: ${{ steps.docker-meta.outputs.labels }}
                  push: true
