name: "Build Consolidated Image"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and Push"
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 #v6.15.0
        if: github.event_name == 'pull_request'
        with:
          context: ./actions
          file: actions/Dockerfile
          tags: |
            ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${{ github.event.pull_request.head.sha }}
            ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:latest
          push: true
      - name: "Build and Push"
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 #v6.15.0
        if: github.event_name == 'push'
        with:
          context: ./actions
          file: actions/Dockerfile
          tags: |
            ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:sha-${{ github.sha }}
            ghcr.io/grafana/sigma-rule-deployment/sigma-rule-deployer:latest
          push: true

  e2e-convert-and-integrate:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Convert Sigma Rules
        id: converted-rules-output
        uses: grafana/sigma-rule-deployment/actions/convert@latest
        with:
          config_path: "./test/config.yml"
          pretty_print: true
          plugin_packages: pysigma-backend-loki,pysigma-backend-elasticsearch
          all_rules: true

      - name: Integrate Converted Rules
        id: integrated-rules-output
        uses: grafana/sigma-rule-deployment/actions/integrate@latest
        with:
          config_path: "./test/config.yml"
          pretty_print: true
          all_rules: true
          changed_files: ${{ steps.converted-rules-output.outputs.changed_files }}
          deleted_files: ${{ steps.converted-rules-output.outputs.deleted_files }}

