name: "Close Integration Test PR"

on:
  pull_request:
    types:
      - closed

jobs:
  close-integration-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get GitHub App Token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        with:
          github_app: sigma-rule-deployment-app
      - name: Close PR
        env:
          GITHUB_TOKEN: ${{ steps.get-github-app-token.outputs.token }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr close --repo grafana/sigma-rule-deployment-integration-test "integration-test-pr-${GITHUB_PR_NUMBER}" -c "Closed by GitHub Actions, tests completed" -d || true
