name: Validate Renovate Config

on:
  pull_request:
    paths:
      - "renovate.json"
  push:
    branches:
      - main
    paths:
      - "renovate.json"

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          persist-credentials: false
      - name: Validate Renovate Config
        uses: grafana/shared-workflows/actions/validate-renovate-config@4178c5d9a0403e8b8e123baebc66e224d9c4f3cd # v0.1.0

