name: Zizmor Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  security-scan:
    name: Run Zizmor Security Scan
    runs-on: ubuntu-latest
    permissions:
      checks: write # Required for reporting test results and creating check runs
      contents: read
      actions: read # Needed for private repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Run zizmor on all files
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
